import React from 'react'
import Head from 'next/head'

function Seed(props: { slug: string }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 py-10 max-w-3xl mx-auto sm:px-6 sm:py-12 lg:max-w-4xl lg:py-16 lg:px-8 xl:max-w-6xl">
        <article className="prose sm:prose-lg lg:prose-xl xl:prose-xl 2xl:prose-2xl mx-auto">
          <h1>Title here</h1>
          <p>Here we'll load "{props.slug}"</p>
        </article>
      </main>
    </div>
  )
}

Seed.getInitialProps = async (context: { query: { slug: string } }) => {
  const { slug } = context.query

  return { slug }
}

export default Seed
