import React from 'react'
import Head from 'next/head'

import PostTitle from '../../components/PostTitle'
import PostBody from '../../components/PostBody'
import Post from '../../components/Post'

import { GetStaticProps, GetStaticPaths } from 'next'

function Seed({data, content}: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Post>
          <PostTitle title={data.title} author="Bogdan Covrig"/>
          <PostBody>{content}</PostBody>
      </Post>

    </>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch(`${process.env.STRAPI_URL}/api/seeds/`)
  const seeds = await res.json()

  return {
    paths: seeds.data.map((seed: {attributes: {slug: string}}) => ({
      params: {
        slug: seed.attributes.slug,
      },
    })),
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const res = await fetch(`${process.env.STRAPI_URL}/api/seeds?filters[slug][$eq]=${params?.slug}`)
  const seed = await res.json()

  return {
    props: { 
      data: {
        ...seed.data[0].attributes
      },
      content: seed.data[0].attributes.body
    },
  }
}

export default Seed
